/**
 * Curated quote library for Counted.
 * 200 quotes across themes relevant to a life calendar:
 * time, mortality, presence, purpose, courage, growth, love, simplicity.
 * One cycles per day — 200-day rotation before repeating.
 */

export interface Quote {
  text: string;
  author: string;
}

export const QUOTES: Quote[] = [
  // ── Time & Mortality ──────────────────────────────────────────────────────
  { text: "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.", author: "Mark Twain" },
  { text: "It is not that we have a short time to live, but that we waste a good deal of it.", author: "Seneca" },
  { text: "You could leave life right now. Let that determine what you do and say and think.", author: "Marcus Aurelius" },
  { text: "Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.", author: "Steve Jobs" },
  { text: "The days that make us happy make us wise.", author: "John Masefield" },
  { text: "Lost time is never found again.", author: "Benjamin Franklin" },
  { text: "Time is the most valuable thing a man can spend.", author: "Theophrastus" },
  { text: "The trouble is, you think you have time.", author: "Jack Kornfield" },
  { text: "We must use time wisely and forever realize that the time is always ripe to do right.", author: "Nelson Mandela" },
  { text: "Death is not the greatest loss in life. The greatest loss is what dies inside us while we live.", author: "Norman Cousins" },
  { text: "Life is short. Live passionately.", author: "Marc A. Pitman" },
  { text: "Dost thou love life? Then do not squander time, for that is the stuff life is made of.", author: "Benjamin Franklin" },
  { text: "The present moment is the only moment available to us, and it is the door to all moments.", author: "Thích Nhất Hạnh" },
  { text: "Every man dies. Not every man really lives.", author: "William Wallace" },
  { text: "Time and tide wait for no man.", author: "Geoffrey Chaucer" },
  { text: "The time you enjoy wasting is not wasted time.", author: "Bertrand Russell" },
  { text: "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did.", author: "Mark Twain" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "If not now, when?", author: "Hillel the Elder" },

  // ── Presence & Mindfulness ────────────────────────────────────────────────
  { text: "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", author: "Bill Keane" },
  { text: "You must live in the present, launch yourself on every wave, find your eternity in each moment.", author: "Henry David Thoreau" },
  { text: "Be happy in the moment — that's enough. Each moment is all we need, not more.", author: "Mother Teresa" },
  { text: "Realize deeply that the present moment is all you ever have.", author: "Eckhart Tolle" },
  { text: "The present moment always will have been.", author: "Eckhart Tolle" },
  { text: "Life is available only in the present moment.", author: "Thích Nhất Hạnh" },
  { text: "Do not dwell in the past, do not dream of the future — concentrate the mind on the present moment.", author: "Buddha" },
  { text: "The secret of health for both mind and body is not to mourn for the past, nor to worry about the future, but to live the present moment wisely and earnestly.", author: "Buddha" },
  { text: "Wherever you are, be all there.", author: "Jim Elliot" },
  { text: "Nothing is worth more than this day.", author: "Johann Wolfgang von Goethe" },

  // ── Purpose & Meaning ─────────────────────────────────────────────────────
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived.", author: "Ralph Waldo Emerson" },
  { text: "Life is never made unbearable by circumstances, but only by lack of meaning and purpose.", author: "Viktor Frankl" },
  { text: "Those who have a why to live can bear with almost any how.", author: "Viktor Frankl" },
  { text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { text: "Your work is to discover your world and then with all your heart give yourself to it.", author: "Buddha" },
  { text: "The purpose of life, as far as I can tell, is to find a mode of being that's so meaningful that the fact that life is suffering is no longer relevant.", author: "Jordan Peterson" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { text: "Man is not fully conditioned and determined; he determines himself whether he gives in to conditions or stands up to them.", author: "Viktor Frankl" },
  { text: "What man actually needs is not a tensionless state but rather the striving and struggling for some goal worthy of him.", author: "Viktor Frankl" },

  // ── Action & Starting ─────────────────────────────────────────────────────
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "In any moment of decision, the best thing you can do is the right thing, the next best thing is the wrong thing, and the worst thing you can do is nothing.", author: "Theodore Roosevelt" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "Just do it.", author: "Nike" },
  { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },

  // ── Stoicism ──────────────────────────────────────────────────────────────
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius" },
  { text: "If it is not right do not do it; if it is not true do not say it.", author: "Marcus Aurelius" },
  { text: "When you arise in the morning, think of what a privilege it is to be alive — to think, to enjoy, to love.", author: "Marcus Aurelius" },
  { text: "Never esteem anything as of advantage to you that will make you break your word or lose your self-respect.", author: "Marcus Aurelius" },
  { text: "Each day provides its own gifts.", author: "Marcus Aurelius" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca" },
  { text: "We suffer more in imagination than in reality.", author: "Seneca" },
  { text: "Life is long if you know how to use it.", author: "Seneca" },
  { text: "Omnia aliena sunt, tempus tantum nostrum est. (All things are alien; time alone belongs to us.)", author: "Seneca" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus" },
  { text: "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", author: "Epictetus" },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
  { text: "We cannot choose our external circumstances, but we can always choose how we respond to them.", author: "Epictetus" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { text: "Men are disturbed not by the things which happen, but by the opinions about the things.", author: "Epictetus" },

  // ── Courage & Resilience ──────────────────────────────────────────────────
  { text: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "The oak fought the wind and was broken, the willow bent when it must and survived.", author: "Robert Jordan" },
  { text: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
  { text: "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.", author: "Helen Keller" },
  { text: "It is not the mountain we conquer, but ourselves.", author: "Edmund Hillary" },
  { text: "Out of suffering have emerged the strongest souls.", author: "Khalil Gibran" },
  { text: "The world breaks everyone, and afterward, some are strong at the broken places.", author: "Ernest Hemingway" },
  { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { text: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "The strongest people are not those who show strength in front of us but those who win battles we know nothing about.", author: "Unknown" },
  { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
  { text: "What does not kill me makes me stronger.", author: "Friedrich Nietzsche" },
  { text: "Rock bottom became the solid foundation on which I rebuilt my life.", author: "J.K. Rowling" },

  // ── Growth & Learning ─────────────────────────────────────────────────────
  { text: "The only way out is through.", author: "Robert Frost" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "Education is not the filling of a pail, but the lighting of a fire.", author: "William Butler Yeats" },
  { text: "Anyone who stops learning is old, whether at twenty or eighty.", author: "Henry Ford" },
  { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
  { text: "Develop a passion for learning. If you do, you will never cease to grow.", author: "Anthony J. D'Angelo" },
  { text: "Growth is the only evidence of life.", author: "John Henry Newman" },
  { text: "What we fear of doing most is usually what we most need to do.", author: "Ralph Waldo Emerson" },
  { text: "Comfort is the enemy of progress.", author: "P.T. Barnum" },
  { text: "Change is the end result of all true learning.", author: "Leo Buscaglia" },
  { text: "One can choose to go back toward safety or forward toward growth. Growth must be chosen again and again; fear must be overcome again and again.", author: "Abraham Maslow" },
  { text: "The goal of life is to make your heartbeat match the beat of the universe.", author: "Joseph Campbell" },

  // ── Happiness & Gratitude ─────────────────────────────────────────────────
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "Gratitude turns what we have into enough.", author: "Anonymous" },
  { text: "Joy is not in things; it is in us.", author: "Richard Wagner" },
  { text: "Count your age by friends, not years. Count your life by smiles, not tears.", author: "John Lennon" },
  { text: "The most important thing is to enjoy your life — to be happy — it's all that matters.", author: "Audrey Hepburn" },
  { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
  { text: "For every minute you are angry you lose sixty seconds of happiness.", author: "Ralph Waldo Emerson" },
  { text: "Folks are usually about as happy as they make their minds up to be.", author: "Abraham Lincoln" },
  { text: "There is no path to happiness: happiness is the path.", author: "Buddha" },
  { text: "Be thankful for what you have; you'll end up having more.", author: "Oprah Winfrey" },
  { text: "Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for.", author: "Epicurus" },

  // ── Love & Connection ─────────────────────────────────────────────────────
  { text: "The best thing to hold onto in life is each other.", author: "Audrey Hepburn" },
  { text: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
  { text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare" },
  { text: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", author: "Lao Tzu" },
  { text: "The measure of love is to love without measure.", author: "Saint Francis de Sales" },
  { text: "At the end of the day, it's not about what you have or even what you've accomplished. It's about who you've lifted up.", author: "Denzel Washington" },
  { text: "No man is an island.", author: "John Donne" },
  { text: "In the end, the love you take is equal to the love you make.", author: "Paul McCartney" },
  { text: "Life without love is like a tree without blossoms or fruit.", author: "Khalil Gibran" },
  { text: "Kindness is a language which the deaf can hear and the blind can see.", author: "Mark Twain" },

  // ── Simplicity & Enough ──────────────────────────────────────────────────
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "It is not how much we have, but how much we enjoy, that makes happiness.", author: "Charles Spurgeon" },
  { text: "Have nothing in your home that you do not know to be useful or believe to be beautiful.", author: "William Morris" },
  { text: "Not what we have but what we enjoy constitutes our abundance.", author: "Epicurus" },
  { text: "The greatest wealth is to live content with little.", author: "Plato" },
  { text: "Less is more.", author: "Ludwig Mies van der Rohe" },
  { text: "Enough is a feast.", author: "Buddhist Proverb" },
  { text: "He is richest who is content with the least.", author: "Socrates" },

  // ── Doing & Work ─────────────────────────────────────────────────────────
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "The only place success comes before work is in the dictionary.", author: "Vince Lombardi" },
  { text: "Genius is one percent inspiration, ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "I'm a great believer in luck, and I find the harder I work, the more I have of it.", author: "Thomas Jefferson" },
  { text: "Do what you love and you'll never work a day in your life.", author: "Marc Anthony" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
  { text: "Excellence is not a destination; it is a continuous journey that never ends.", author: "Brian Tracy" },
  { text: "Work like there is someone working 24 hours a day to take it all away from you.", author: "Mark Cuban" },
  { text: "To give anything less than your best is to sacrifice the gift.", author: "Steve Prefontaine" },
  { text: "If you genuinely want something, don't wait for it — teach yourself to be impatient.", author: "Gurbaksh Chahal" },

  // ── Perspective & Wisdom ─────────────────────────────────────────────────
  { text: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
  { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "It's not what you look at that matters, it's what you see.", author: "Henry David Thoreau" },
  { text: "The most beautiful things in the world cannot be seen or touched, they are felt with the heart.", author: "Antoine de Saint-Exupéry" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "Life is a mirror and will reflect back to the thinker what he thinks into it.", author: "Ernest Holmes" },
  { text: "We don't see things as they are, we see them as we are.", author: "Anaïs Nin" },
  { text: "The world is a book, and those who do not travel read only one page.", author: "Saint Augustine" },
  { text: "To see the world, things dangerous to come to, to see behind walls, draw closer, to find each other, and to feel. That is the purpose of life.", author: "James Thurber" },
  { text: "Wonder is the beginning of wisdom.", author: "Socrates" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "One of the greatest diseases is to be nobody to anybody.", author: "Mother Teresa" },
  { text: "What you do speaks so loudly that I cannot hear what you say.", author: "Ralph Waldo Emerson" },

  // ── Dreams & Vision ──────────────────────────────────────────────────────
  { text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { text: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
  { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
  { text: "Shoot for the moon. Even if you miss, you'll land among the stars.", author: "Les Brown" },
  { text: "The only limits are, as always, those of vision.", author: "James Broughton" },
  { text: "If you can dream it, you can do it.", author: "Walt Disney" },

  // ── Self & Identity ──────────────────────────────────────────────────────
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "Know yourself. Know your worth.", author: "Drake" },
  { text: "You are enough, just as you are.", author: "Meghan Markle" },
  { text: "Your life is your message to the world. Make it inspiring.", author: "Lorrin L. Lee" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { text: "Don't let others define you. Define yourself.", author: "Khloe Kardashian" },
  { text: "The strongest factor for success is self-esteem: believing you can do it, believing you deserve it, believing you will get it.", author: "Unknown" },

  // ── Nature & Universe ────────────────────────────────────────────────────
  { text: "Look deep into nature, and then you will understand everything better.", author: "Albert Einstein" },
  { text: "In every walk with nature, one receives far more than he seeks.", author: "John Muir" },
  { text: "The good life is one inspired by love and guided by knowledge.", author: "Bertrand Russell" },
  { text: "Those who contemplate the beauty of the earth find reserves of strength that will endure as long as life lasts.", author: "Rachel Carson" },
  { text: "Heaven is under our feet as well as over our heads.", author: "Henry David Thoreau" },

  // ── Short & Sharp ────────────────────────────────────────────────────────
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "Think different.", author: "Apple" },
  { text: "Make it work.", author: "Tim Gunn" },
  { text: "Just begin.", author: "Anonymous" },
  { text: "One day or day one. You decide.", author: "Anonymous" },
  { text: "Show up.", author: "Woody Allen" },
  { text: "Burn bright.", author: "Anonymous" },
  { text: "Be kind. Be brave. Be you.", author: "Anonymous" },
  { text: "Do it scared.", author: "Ruth Soukup" },
  { text: "Make it count.", author: "Anonymous" },
  { text: "Every day is a gift.", author: "Anonymous" },
  { text: "Choose joy.", author: "Anonymous" },
  { text: "Keep going.", author: "Anonymous" },
  { text: "Breathe. You've got this.", author: "Anonymous" },
];
